typedef enum
{
	CMD_ERROR = 0x0,
	CMD_OK = 0x1,
	CMD_GET_ICE_REVOLUTION = 0x10,
	CMD_GET_CURRENT_TIME = 0x11,
	CMD_GET_EVENT_TIME = 0x12,
	CMD_GET_MASS_STATUS = 0x13,
	CMD_GET_ENGINE_STATUS = 0x14,
	CMD_GET_CAR_SPEED = 0x15,
}CMD;


typedef enum
{
	BLOCK_MANAGEMENT_ID = 0x41,
	CAR_ID = 0x42,
}NET_ID;
